version: "3.7"
services:
  karen:
    build:
      dockerfile: karen/Dockerfile
      context: "."
    ports:
      - 52736:52736
  bot:
    build:
      dockerfile: bot/Dockerfile
      context: "."
    depends_on:
      - karen
