[tool.poetry]
name = "Villager-Bot"
version = "0.0.1"
description = ""
authors = ["Milo Weinberg <iapetus011@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.3"
classy-json = "^3.2.1"
"discord.py" = "^1.7.2"
pydantic = "^1.8.2"
asyncpg = "^0.23.0"
aiofiles = "^0.7.0"
aiohttp = "^3.7.4"
orjson = "^3.5.2"
arrow = "^1.1.0"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127